### ISSUE TITLE
No or fractured images / base64 decode problem.

### ISSUE THREAD

**Issue by peko** [testimio/mhtml-parser#11] opened 2019-11-26 08:13 UTC
Seems like base64 decoding have issue with new lines in encoded body like this:

```
------MultipartBoundary--O7kVRKVfmd1nCNuKBaQmK8j3jZ9Bb9MhcZjFQGEJ91----
Content-Type: image/png
Content-Transfer-Encoding: base64
Content-Location: http://aurora24.ru/bitrix/images/aspro.next/themes/mobile_menu1.png

iVBORw0KGgoAAAANSUhEUgAAAIoAAABxCAMAAAA9DMuMAAAABGdBTUEAALGPC/xhBQAAAAFzUkdC
AK7OHOkAAAERUExUReLi4tDQ0N3d3dbW1tLS0svLy9ra2v///+Xl5ePj487OzuTk5L29verq6tnZ
2fz8/MfHx+Dg4MHBwevr69PT0+bm5mVlZff395GRkdTU1PHx8cTExD8/P2NjYzo6OsbGxs/Pz97e
...
```

Simplest solution is to replace the decoder with classic one, with new line removing.

https://github.com/testimio/mhtml-parser/blob/master/src/decoder.js#L6

```
return Buffer.from(body.toString().replace(/\r|\n/g, ''), 'base64');
```

**Comment by benjamingr** [comment] 2019-11-27 23:14
Hey, 


Sorry for the late response (I am between conferences) - can you send over a reproducing HTML file? I will gladly debug this and fix it.

`64` gave a significant improvement over `Buffer.from` in benchmarks so I don't want to opt out just yet.

I am also OK with having an environment variable for this that opts out of 64 but I would rather avoid the perf hit if I can.

**Comment by benjamingr** [comment] 2020-01-15 08:59
ping?

**Comment by benjamingr** [comment] 2020-10-07 08:28
Hey, can you please let me know if the issue is now fixed?

**Comment by javamonn** [comment] 2021-03-21 22:02
@benjamingr I can reproduce this with [demos/wikipedia.mhtml](https://github.com/testimio/mhtml-parser/blob/master/demos/wikipedia.mhtml), both when using `64` and the fallback / native decoder. Swapping out the decoder line to strip newlines as recommended in OP here fixes the issue for me. Let me know if any other environment info is useful.

**Comment by benjamingr** [comment] 2021-03-22 08:31
PR to make this configurable welcome

**Comment by benjamingr** [comment] 2021-03-22 08:31
Or actually, probably fine to just remove `64` it doesn't look particularly well maintained

**Closed** 2021-05-25 08:19 UTC
